name: cc_uffs
description: Aplicativo móvel para uso de alunos, professores e técnicos do curso de Ciência da Computação da UFFS.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.8
  transparent_image: ^1.0.0
  site_cc_parser:
    git:
      url: https://github.com/fersasil/parser_cc_uffs_dart
      ref: 16d7d5fe76070d34716a8775df0f815a3448f603
  #cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-branco.png
    - assets/images/logo-verde.png
    - assets/images/logo.png
    - assets/images/full-logo.png

